apiVersion: v1
kind: Service
metadata:
  name: {{ template "qmig.app.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "qmig.app.labels" . | nindent 4 }}
  {{- with .Values.app.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.app.service.type }}
  ports:
    - port: {{ .Values.app.service.port }}
      targetPort: {{ .Values.app.name }}-http
      protocol: TCP
  selector:
    {{- include "qmig.app.selectorLabels" . | nindent 4 }}
