apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: "disk-csi"
provisioner: docker.io/hostpath
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
---
# Source: qmig/templates/air/air-pv.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: qmig-shared
spec:
  capacity:
    storage: "5Gi"
  accessModes:
    - ReadWriteMany
  storageClassName: disk-csi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: {{LOCAL_PATH}}
---
# Source: qmig/templates/air/air-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/name: qmig
  name: qmig-shared
  namespace: qmig-ns
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "disk-csi"
  volumeName: qmig-shared
  resources:
    requests:
      storage: "5Gi"
