{{- if .Values.eng.ingress.enabled -}}
{{- $fullName := include "qmig.eng.fullname" . -}}
{{- $svcPort := .Values.eng.service.port -}}
{{- if .Values.eng.ingress.className }}
  {{- if not (hasKey .Values.eng.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.eng.ingress.annotations "kubernetes.io/ingress.class" .Values.eng.ingress.className}}
  {{- end }}
{{- end }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "qmig.eng.labels" . | nindent 4 }}
  {{- with .Values.eng.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.eng.ingress.className }}
  ingressClassName: {{ .Values.eng.ingress.className }}
  {{- end }}
  {{- if .Values.eng.ingress.tls }}
  tls:
    {{- range .Values.eng.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- if .Values.eng.ingress.host }}
    - host: {{ .Values.eng.ingress.host | quote }}
      http:
    {{- else }}
    - http:
    {{- end }}
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
{{- end }}