{{- if .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ include "qmig.gateway.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "qmig.gateway.labels" . | nindent 4 }}
  {{- with .Values.gateway.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  gatewayClassName: {{ .Values.gateway.gatewayClassName }}
  listeners:
  - name: http
    protocol: HTTP
    port: 80
    {{- if .Values.gateway.allowedRoutes }}
    allowedRoutes:
      {{- toYaml .Values.gateway.allowedRoutes | nindent 6 }}
    {{- end }}
{{- end }}