{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "qmig.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "qmig.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: true
{{- end }}
---
{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "qmig.serviceAccountName" . }}-role
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "qmig.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources:
      - pods
      - secrets
    verbs: ["get", "list", "create", "update", "delete"]
  - apiGroups: ["batch"]
    resources:
      - jobs
      - cronjobs
    verbs: ["get", "list", "watch", "create", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "qmig.serviceAccountName" . }}-rolebinding
  namespace: {{ .Release.Namespace }} 
  labels:
    {{- include "qmig.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "qmig.serviceAccountName" . }}-role
subjects:
- namespace: {{ .Release.Namespace }} 
  kind: ServiceAccount
  name: {{ template "qmig.serviceAccountName" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "qmig.serviceAccountName" . }}-crole
  labels:
    {{- include "qmig.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources:
      - namespaces
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "qmig.serviceAccountName" . }}-crolebinding
  labels:
    {{- include "qmig.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "qmig.serviceAccountName" . }}-crole
subjects:
- namespace: {{ .Release.Namespace }} 
  kind: ServiceAccount
  name: {{ template "qmig.serviceAccountName" . }}
{{- end }}