{{- $PROJECT_ID := .Values.secret.data.PROJECT_ID | required ".Values.secret.data.PROJECT_ID is required." -}}
{{- $POSTGRES_PASSWORD := include "qmig.db.password" . -}}
{{- $PROJECT_NAME := .Values.secret.data.PROJECT_NAME | required ".Values.secret.data.PROJECT_NAME is required." -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "qmig.secret" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "qmig.secret.labels" . | nindent 4 }}
  {{- with .Values.secret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  PROJECT_ID: {{ $PROJECT_ID | toString | b64enc | quote }}
  POSTGRES_PASSWORD: {{ $POSTGRES_PASSWORD | toString | b64enc | quote }}
  PROJECT_NAME: {{ $PROJECT_NAME | b64enc | quote }}