{{- $PROJECT_ID := .Values.secret.data.PROJECT_ID | required ".Values.secret.data.PROJECT_ID is required." -}}
{{- $POSTGRES_PASSWORD := include "qmig.db.password" . -}}
{{- $PROJECT_NAME := .Values.secret.data.PROJECT_NAME | required ".Values.secret.data.PROJECT_NAME is required." -}}
{{- $REDIS_PASS := .Values.secret.data.REDIS_PASS | required ".Values.secret.data.REDIS_PASS  is required." -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "qmig.secret" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "qmig.labels" . | nindent 4 }}
data:
  PROJECT_ID: {{ $PROJECT_ID | toString | b64enc | quote }}
  POSTGRES_PASSWORD: {{ $POSTGRES_PASSWORD | toString | b64enc | quote }}
  PROJECT_NAME: {{ $PROJECT_NAME | b64enc | quote }}
  REDIS_PASS: {{ $REDIS_PASS | toString | b64enc | quote }}