apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "qmig.msg.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "qmig.msg.labels" . | nindent 4 }}
  {{- with .Values.msg.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  keydb.conf: |-
    {{- if .Values.msg.keyDBConfig.stringOverride }}
    {{- .Values.msg.keyDBConfig.stringOverride | nindent 4 }}
    {{- else }}
    {{- tpl (.Files.Get "files/msg-keys.conf") . | nindent 4 }}
    {{- end }}