{{- if and .Values.airflow.enabled .Values.airflow.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "qmig.airflow.fullname" . }}-pod-launcher-role
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "qmig.airflow.labels" . | nindent 4 }}
  {{- if .Values.airflow.annotations }}
  annotations: {{- toYaml .Values.airflow.annotations | nindent 4 }}
  {{- end }}
rules:
  - apiGroups:
      - ""
    resources:
      - "pods"
    verbs:
      - "create"
      - "list"
      - "get"
      - "patch"
      - "watch"
      - "delete"
  - apiGroups:
      - ""
    resources:
      - "pods/log"
    verbs:
      - "get"
  - apiGroups:
      - ""
    resources:
      - "pods/exec"
    verbs:
      - "create"
      - "get"
  - apiGroups:
      - ""
    resources:
      - "events"
    verbs:
      - "list"
{{- end }}
---
{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "qmig.airflow.fullname" . }}-pod-log-reader-role
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "qmig.airflow.labels" . | nindent 4 }}
  {{- if .Values.airflow.annotations }}
  annotations: {{- toYaml .Values.airflow.annotations | nindent 4 }}
  {{- end }}
rules:
  - apiGroups:
      - ""
    resources:
      - "pods"
    verbs:
      - "list"
      - "get"
      - "watch"
  - apiGroups:
      - ""
    resources:
      - "pods/log"
    verbs:
      - "get"
      - "list"
{{- end }}
---
{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "qmig.airflow.fullname" . }}-pod-launcher-rolebinding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "qmig.airflow.labels" . | nindent 4 }}
  {{- if .Values.airflow.annotations }}
  annotations: {{- toYaml .Values.airflow.annotations | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "qmig.airflow.fullname" . }}-pod-launcher-role
subjects:
  - kind: ServiceAccount
    name: {{ template "qmig.serviceAccountName" . }}
    namespace: "{{ .Release.Namespace }}"
{{- end }}
---
{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: "{{ .Release.Namespace }}"
  name: {{ include "qmig.airflow.fullname" . }}-pod-log-reader-rolebinding
  labels:
    {{- include "qmig.airflow.labels" . | nindent 4 }}
  {{- if .Values.airflow.annotations }}
  annotations: {{- toYaml .Values.airflow.annotations | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "qmig.airflow.fullname" . }}-pod-log-reader-role
subjects:
  - kind: ServiceAccount
    name: {{ template "qmig.serviceAccountName" . }}
    namespace: "{{ .Release.Namespace }}"
{{- end }}