{{- if .Values.airflow.enabled }}
{{- $airflow_secret_key := .Values.airflow.secret.data.airflow_secret_key | default (randAlphaNum 32) -}}
{{- $airflow_fernet_key := .Values.airflow.secret.data.airflow_fernet_key | default (randAlphaNum 32) -}}
{{- $airflow_password := .Values.airflow.secret.data.airflow_password | required ".Values.airflow.secret.data.airflow_password is required." -}}
{{- $host := (include "qmig.db.hostname" .) }}
{{- $metadataPort := include "qmig.db.port" . | toString }}
{{- $database := "postgres" }}
{{- $user := (include "qmig.db.username" .) }}
{{- $pass := (include "qmig.db.password" .) }}
{{- $port := (include "qmig.db.port" .) }}
{{- $scheme := "postgresql" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "qmig.airflow.secret" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "qmig.airflow.labels" . | nindent 4 }}
  {{- if .Values.airflow.annotations }}
  annotations: {{- toYaml .Values.airflow.annotations | nindent 4 }}
  {{- end }}
data:
  airflow-secret-key: {{ $airflow_secret_key | toString | b64enc | quote }}
  airflow-fernet-key: {{ $airflow_fernet_key | toString | b64enc | quote }}
  airflow-password: {{ $airflow_password | b64enc | quote }}
  connection: {{ urlJoin (dict "scheme" $scheme "userinfo" (printf "%s:%s" ($user | urlquery) ($pass | urlquery) ) "host" (printf "%s:%s" $host $port) "path" (printf "/%s" $database)) | b64enc | quote }}
{{- end }}