{{- if .Values.airflow.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "qmig.airflow.fullname" . }}-webserver
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "qmig.airflow.labels" . | nindent 4 }}
    component: webserver
  {{- if .Values.airflow.webserver.annotations }}
  annotations: {{- toYaml .Values.airflow.webserver.annotations | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.airflow.webserver.service.type }}
  selector:
    {{- include "qmig.airflow.selectorLabels" . | nindent 4 }}
    component: webserver
  ports:
    - port: {{ .Values.airflow.webserver.service.port }}
      targetPort: airflow-ui
      protocol: TCP
{{- end }}